# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: 'anpix'
      MYSQL_PASS: 'pass'
      MYSQL_ROOT_PASSWORD: localhost
    volumes:
      - mysql-data:/var/lib/mysql:rw
  
  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: localhost

#  adminer:
#    container_name: mysql-adminer
#    hostname: mysql-adminer
#    depends_on:
#    - mysql
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  mysql-data: