apiVersion: v1
kind: Namespace
metadata:
  name: catalina
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalina
  namespace: catalina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalina
  template:
    metadata:
      labels:
        app: catalina
    spec:
      containers:
        - name: catalina
          image: sickcodes/docker-osx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10022
            - containerPort: 50922
          env:
            - name: DISPLAY
              value: ":0.0"
          volumeMounts:
            - name: x11-unix
              mountPath: /tmp/.X11-unix
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 4Gi
              cpu: 2000m
      volumes:
        - name: x11-unix
          hostPath:
            path: /tmp/.X11-unix
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: catalina
  namespace: catalina
spec:
  type: NodePort
  selector:
    app: catalina
  ports:
    - port: 10022
      targetPort: 10022
      nodePort: 32022
    - port: 50922
      targetPort: 50922
      nodePort: 36022
