apiVersion: v1
kind: Namespace
metadata:
  name: kali
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali
  namespace: kali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kali
  template:
    metadata:
      labels:
        app: kali
    spec:
      containers:
        - name: kali
          image: kalilinux/kali-rolling:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "sleep infinity"]
          tty: true
          stdin: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: kali
  namespace: kali
spec:
  type: ClusterIP
  selector:
    app: kali
  ports:
    - port: 22
      targetPort: 22
