apiVersion: v1
kind: Namespace
metadata:
  name: macosx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macosx
  namespace: macosx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: macosx
  template:
    metadata:
      labels:
        app: macosx
    spec:
      containers:
        - name: macosx
          image: sickcodes/docker-osx:auto
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10022
            - containerPort: 50922
          env:
            - name: DISPLAY
              value: ":0.0"
          volumeMounts:
            - name: x11-unix
              mountPath: /tmp/.X11-unix
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 4Gi
              cpu: 2000m
      volumes:
        - name: x11-unix
          hostPath:
            path: /tmp/.X11-unix
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: macosx
  namespace: macosx
spec:
  type: NodePort
  selector:
    app: macosx
  ports:
    - port: 10022
      targetPort: 10022
      nodePort: 31022
    - port: 50922
      targetPort: 50922
      nodePort: 35022
