version: '3.2'

services:

  cloudflared:
    container_name: cloudflared
    hostname: cloudflared
    image: cloudflare/cloudflared:latest
    command:  tunnel --no-autoupdate run --token YOUR_TOKEN_HERE
    #restart: always