services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - /dev/db/postgres:/var/lib/postgresql/data # mkdir postgres_db_data before docker compose up
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 5051:80

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    hostname: pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: localhost@anpix.com.br
      PGADMIN_DEFAULT_PASSWORD: localhost