apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          command:
            ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 500m
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-manager
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-manager
  template:
    metadata:
      labels:
        app: redis-manager
    spec:
      containers:
        - name: redis-manager
          image: lukiya/redismanager:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 500m
          ports:
            - containerPort: 16379
          volumeMounts:
            - name: redis-manager-storage
              mountPath: /app
      volumes:
        - name: redis-manager-storage
          persistentVolumeClaim:
            claimName: redis-manager-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-manager-pvc
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-manager
  namespace: redis
spec:
  type: NodePort
  selector:
    app: redis-manager
  ports:
    - port: 16379
      targetPort: 16379
      nodePort: 31639
